import React from 'react';
import {
    AlertCircle,
    AlertTriangle,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    AudioLines,
    Award,
    BadgeCheck,
    Ban,
    BarChart3,
    Bell,
    Braces,
    Brain,
    Calendar,
    Camera,
    Captions,
    Check,
    CheckCircle2,
    ChevronDown,
    ChevronRight,
    CircleUserRound,
    Clock,
    Cloud,
    Code2,
    Cookie,
    Copy,
    CreditCard,
    DollarSign,
    Download,
    Edit3,
    Eye,
    EyeOff,
    Feather,
    FileText,
    FileUp,
    Flag,
    FlaskConical,
    Folder,
    FolderInput,
    FolderOpen,
    FolderPlus,
    Gauge,
    Gavel,
    GraduationCap,
    Grid3x3,
    Headphones,
    HelpCircle,
    Image,
    Info,
    KeyRound,
    LayoutDashboard,
    List,
    Loader2,
    Lock,
    Mail,
    MailCheck,
    MapPin,
    Megaphone,
    Menu,
    MessageCircle,
    MessageSquare,
    Mic,
    MicOff,
    Monitor,
    Moon,
    MoreVertical,
    Music,
    Navigation,
    Network,
    Package,
    Pause,
    Pencil,
    Phone,
    PhoneCall,
    PhoneOff,
    Play,
    PlayCircle,
    Plus,
    Puzzle,
    RefreshCw,
    RotateCcw,
    ScrollText,
    Search,
    SearchX,
    Send,
    Settings,
    Share,
    Share2,
    Shield,
    ShieldCheck,
    Smartphone,
    Sparkles,
    Square,
    Star,
    Stethoscope,
    StickyNote,
    Sun,
    Tablet,
    ThumbsDown,
    ThumbsUp,
    Trash2,
    UploadCloud,
    User,
    UserCog,
    UserPlus,
    Users,
    Volume2,
    X,
    Zap,
    ZoomIn,
    HelpCircle as IconoDesconocido,
    type LucideIcon
} from 'lucide-react';

/**
 * Puente de migracion: pinta con lucide los iconos que el codigo nombraba con
 * ligaduras de Material Symbols.
 *
 * Existe para poder retirar la fuente de iconos (3,87 MB completa) sin tocar
 * los ~190 puntos de uso a mano ni romper los iconos que vienen de DATOS
 * (folder.icon, item.icon, tpl.icon): el mapa nombre -> componente vive aqui y
 * en ningun otro sitio.
 *
 * Un nombre que no este en el mapa pinta un interrogante en desarrollo y avisa
 * por consola, en vez de mostrar el nombre como texto crudo, que era el fallo
 * silencioso de la fuente de ligaduras.
 */
const MAPA: Record<string, LucideIcon> = {
    "account_circle": CircleUserRound,
    "add": Plus,
    "admin_panel_settings": UserCog,
    "analytics": BarChart3,
    "arrow_back": ArrowLeft,
    "arrow_forward": ArrowRight,
    "arrow_upward": ArrowUp,
    "auto_awesome": Sparkles,
    "block": Ban,
    "bolt": Zap,
    "calendar_today": Calendar,
    "call": Phone,
    "call_end": PhoneOff,
    "chat": MessageSquare,
    "chat_bubble": MessageCircle,
    "check": Check,
    "check_circle": CheckCircle2,
    "chevron_right": ChevronRight,
    "close": X,
    "closed_caption": Captions,
    "cloud": Cloud,
    "cloud_sync": RefreshCw,
    "cloud_upload": UploadCloud,
    "code": Code2,
    "content_copy": Copy,
    "cookie": Cookie,
    "create_new_folder": FolderPlus,
    "dark_mode": Moon,
    "dashboard": LayoutDashboard,
    "data_object": Braces,
    "delete": Trash2,
    "description": FileText,
    "desktop_windows": Monitor,
    "dialpad": Grid3x3,
    "download": Download,
    "drive_file_move": FolderInput,
    "edit": Pencil,
    "edit_note": Edit3,
    "error": AlertCircle,
    "expand_more": ChevronDown,
    "extension": Puzzle,
    "flag": Flag,
    "flask": FlaskConical,
    "folder": Folder,
    "folder_open": FolderOpen,
    "gavel": Gavel,
    "graphic_eq": AudioLines,
    "group": Users,
    "group_work": Users,
    "headset_mic": Headphones,
    "help": HelpCircle,
    "history_edu": Feather,
    "hub": Network,
    "image": Image,
    "info": Info,
    "inventory_2": Package,
    "ios_share": Share,
    "light_mode": Sun,
    "list": List,
    "location_on": MapPin,
    "lock": Lock,
    "lock_reset": KeyRound,
    "lyrics": Music,
    "mail": Mail,
    "mark_email_read": MailCheck,
    "menu": Menu,
    "mic": Mic,
    "mic_off": MicOff,
    "more_vert": MoreVertical,
    "navigation": Navigation,
    "note": StickyNote,
    "notifications": Bell,
    "pause": Pause,
    "payments": CreditCard,
    "person": User,
    "person_add": UserPlus,
    "phone_iphone": Smartphone,
    "photo_camera": Camera,
    "play_arrow": Play,
    "play_circle": PlayCircle,
    "point_of_sale": DollarSign,
    "progress_activity": Loader2,
    "psychology": Brain,
    "refresh": RefreshCw,
    "replay": RotateCcw,
    "schedule": Clock,
    "school": GraduationCap,
    "search": Search,
    "search_off": SearchX,
    "send": Send,
    "settings": Settings,
    "share": Share2,
    "shield": Shield,
    "shield_person": ShieldCheck,
    "smartphone": Smartphone,
    "speaker_phone": Megaphone,
    "speed": Gauge,
    "star": Star,
    "stethoscope": Stethoscope,
    "stop": Square,
    "summarize": ScrollText,
    "sync": RefreshCw,
    "tablet": Tablet,
    "thumb_down": ThumbsDown,
    "thumb_up": ThumbsUp,
    "upload_file": FileUp,
    "verified": BadgeCheck,
    "verified_user": ShieldCheck,
    "visibility": Eye,
    "visibility_off": EyeOff,
    "volume_up": Volume2,
    "warning": AlertTriangle,
    "wifi_calling_3": PhoneCall,
    "workspace_premium": Award,
    "zoom_in": ZoomIn,
};

interface MSymbolProps {
    name: string;
    size?: number;
    className?: string;
    strokeWidth?: number;
    /** Rellena el glifo, como 'FILL' 1 en Material Symbols. */
    fill?: boolean;
}

export const MSymbol: React.FC<MSymbolProps> = ({ name, size = 24, className, strokeWidth = 1.5, fill = false }) => {
    const Icono = MAPA[name];
    if (!Icono) {
        if (import.meta.env?.DEV) console.warn('[MSymbol] icono sin mapear: ' + name);
        return <IconoDesconocido size={size} className={className} strokeWidth={strokeWidth} aria-hidden="true" />;
    }
    return <Icono size={size} className={className} strokeWidth={strokeWidth} fill={fill ? 'currentColor' : 'none'} aria-hidden="true" />;
};
